# Generated by Django 4.2.5 on 2023-10-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
