# Generated by Django 4.2.5 on 2023-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmprendimiento', models.CharField(max_length=100)),
                ('correoEmprendimiento', models.EmailField(max_length=254, unique=True)),
                ('passEmprendimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
