# Generated by Django 4.2.5 on 2023-10-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_emprendimiento_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprendimiento',
        ),
    ]
