# Generated by Django 4.2.6 on 2023-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
