# Generated by Django 4.2.6 on 2023-10-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
